# tensorflow reduce_mean 함수 테스트

reduce_mean(

    input_tensor,
    axis=None,
    keep_dims=False,
    name=None,
    reduction_indices=None
)

https://www.tensorflow.org/api_docs/python/tf/reduce_mean

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
sess = tf.Session()

In [3]:
x = [[1.,1.,1.]
   , [2.,2.,2.]]
np.array(x).shape

(2, 3)

In [4]:
m = tf.reduce_mean(x)
print(sess.run(m), m.shape)

1.5 ()


In [5]:
m = tf.reduce_mean(x, 0)
print(sess.run(m), m.shape)

[ 1.5  1.5  1.5] (3,)


In [6]:
m = tf.reduce_mean(x, 1)
print(sess.run(m), m.shape)

[ 1.  2.] (2,)


In [7]:
y = [
        [
            [1.,1.,1.,1.]
          , [2.,2.,2.,2.]
          , [3.,3.,3.,3.]
        ]
     , [
            [4.,4.,4.,4.]
          , [5.,5.,5.,5.]
          , [6.,6.,6.,6.]
       ]
    ]
np.array(y).shape

(2, 3, 4)

In [8]:
m = tf.reduce_mean(y)
print(sess.run(m), m.shape)

3.5 ()


In [9]:
m = tf.reduce_mean(y, 0)
print(sess.run(m), m.shape)

[[ 2.5  2.5  2.5  2.5]
 [ 3.5  3.5  3.5  3.5]
 [ 4.5  4.5  4.5  4.5]] (3, 4)


In [10]:
m = tf.reduce_mean(y, 1)
print(sess.run(m), m.shape)

[[ 2.  2.  2.  2.]
 [ 5.  5.  5.  5.]] (2, 4)


In [11]:
m = tf.reduce_mean(y, 2)
print(sess.run(m), m.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]] (2, 3)


In [12]:
m = tf.reduce_mean(y, [0,1])
print(sess.run(m), m.shape)

[ 3.5  3.5  3.5  3.5] (4,)


In [13]:
m = tf.reduce_mean(y, [0,2])
print(sess.run(m), m.shape)

[ 2.5  3.5  4.5] (3,)


In [14]:
m = tf.reduce_mean(y, [-3,2])
print(sess.run(m), m.shape)

[ 2.5  3.5  4.5] (3,)


In [15]:
m = tf.reduce_mean(y, [0,1,2])
print(sess.run(m), m.shape)

3.5 ()
