# tensorflow 함수 테스트

tenserflow 예제에 나오는 함수를 분석해 보자

In [1]:
import tensorflow as tf
import numpy as np

sess=tf.Session()

In [2]:
xy = np.loadtxt('data-03-diabetes.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

- 파이선 함수는 인자명을 붙여주면 인자 순서에 상관없이 지정 가능하다.

In [3]:
X = tf.placeholder(tf.float32, shape=[None, 8])
Y = tf.placeholder(shape=[None, 1], dtype=tf.float32)

In [4]:
W = tf.Variable(tf.random_normal([8, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

- tf.random_normal 값의 형태를 확인해 보자

In [5]:
print(sess.run(tf.random_normal([8, 1])))

[[ 1.65472054]
 [-0.81308734]
 [-1.74599969]
 [-0.84924328]
 [-0.54349178]
 [-0.761841  ]
 [-0.51950985]
 [-0.69634992]]


In [6]:
print(sess.run(tf.random_normal([3, 2, 3])))

[[[-0.29898766 -0.04504935 -2.86510873]
  [ 1.95123196 -1.11632431 -0.2887505 ]]

 [[-1.92635691 -0.18841134 -0.59589523]
  [ 0.71588266 -0.35785562  1.02642155]]

 [[-0.03450118 -0.14677316 -1.2715416 ]
  [ 0.57232499  0.29756737  0.88722825]]]


- 비교연산자를 사용하면 각 요소에 true, false 값이 할당된다.

In [7]:
y_data5 = y_data[:5]
print(y_data5)

[[ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 0.]]


In [8]:
print(y_data5 > 0.5)

[[False]
 [ True]
 [False]
 [ True]
 [False]]


- tf.equal 함수도 true, false 값이 할당된다.

In [9]:
y_data6_10 = y_data[5:10]
print(y_data6_10)
print(sess.run(tf.equal(y_data5, y_data6_10)))

[[ 1.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]]
[[False]
 [False]
 [False]
 [False]
 [ True]]


- tf.cast는 형변환한다

In [10]:
print(sess.run(tf.cast(tf.equal(y_data5, y_data6_10), dtype=tf.float32)))

[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]]


- tf.one_hot 함수

In [11]:
xy2 = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.float32)
y_data2 = xy2[:5, [-1]]
nb_classes = 7
print(y_data2)

[[ 0.]
 [ 0.]
 [ 3.]
 [ 0.]
 [ 0.]]


In [12]:
Y_one_hot = tf.one_hot(y_data2, nb_classes)
print(sess.run(Y_one_hot), "\n", Y_one_hot.shape)

[[[ 1.  0.  0.  0.  0.  0.  0.]]

 [[ 1.  0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  1.  0.  0.  0.]]

 [[ 1.  0.  0.  0.  0.  0.  0.]]

 [[ 1.  0.  0.  0.  0.  0.  0.]]] 
 (5, 1, 7)


- tf.reshape 함수

https://www.tensorflow.org/api_docs/python/tf/reshape

In [13]:
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])
print(sess.run(Y_one_hot), "\n", Y_one_hot.shape)

[[ 1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]] 
 (5, 7)
