# 2주차 실습 lab04 김성헌

## matrix 사용한 multi-variable linear regression

In [1]:
import tensorflow as tf

x_data = [[73., 80., 75.], 
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

X = tf.placeholder(tf.float32, [None, 3])
Y = tf.placeholder(tf.float32, [None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)

train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

0 Cost: 4677.62 
Prediction:
 [[  92.85350037]
 [ 110.0500946 ]
 [ 108.96008301]
 [ 121.86318207]
 [  80.93146515]]
10 Cost: 10.729 
Prediction:
 [[ 153.27619934]
 [ 182.69186401]
 [ 180.52587891]
 [ 199.79663086]
 [ 136.34332275]]
20 Cost: 10.6486 
Prediction:
 [[ 153.44947815]
 [ 182.91830444]
 [ 180.73962402]
 [ 200.02944946]
 [ 136.52047729]]
30 Cost: 10.6112 
Prediction:
 [[ 153.44047546]
 [ 182.92559814]
 [ 180.73747253]
 [ 200.02719116]
 [ 136.5304718 ]]
40 Cost: 10.5739 
Prediction:
 [[ 153.43096924]
 [ 182.93222046]
 [ 180.73468018]
 [ 200.02423096]
 [ 136.53996277]]
50 Cost: 10.5369 
Prediction:
 [[ 153.42149353]
 [ 182.93881226]
 [ 180.73188782]
 [ 200.02128601]
 [ 136.54942322]]
60 Cost: 10.5 
Prediction:
 [[ 153.41203308]
 [ 182.94538879]
 [ 180.72911072]
 [ 200.01831055]
 [ 136.55885315]]
70 Cost: 10.4633 
Prediction:
 [[ 153.40260315]
 [ 182.95195007]
 [ 180.72634888]
 [ 200.01538086]
 [ 136.56826782]]
80 Cost: 10.4268 
Prediction:
 [[ 153.39318848]
 [ 182.95849609]
 [ 1

## 학습데이터 파일을 읽어와서 학습하기. numpy 사용

In [9]:
import tensorflow as tf
import numpy as np

tf.set_random_seed(777) # for reproducibility

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)

x_data = xy[:, :-1]
y_data = xy[:, [-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

X = tf.placeholder(tf.float32, [None, 3])
Y = tf.placeholder(tf.float32, [None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "cost:", cost_val, "\nPrediction\n", hy_val)
        
print("Your score will be " , sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis, feed_dict={X:[[60, 70, 110], [90, 100, 80]]}))

(6, 3) [[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]] 6
(6, 1) [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]]
0 cost: 14293.9 
Prediction
 [[ 41.15560913]
 [ 48.88269806]
 [ 48.77295685]
 [ 49.94010925]
 [ 39.65394974]
 [ 24.05672836]]
10 cost: 2.21472 
Prediction
 [[ 152.60603333]
 [ 182.88232422]
 [ 180.78146362]
 [ 193.70172119]
 [ 141.86672974]
 [  99.41067505]]
20 cost: 1.55542 
Prediction
 [[ 153.35734558]
 [ 183.79142761]
 [ 181.67401123]
 [ 194.67475891]
 [ 142.56079102]
 [  99.92462158]]
30 cost: 1.55164 
Prediction
 [[ 153.35894775]
 [ 183.79919434]
 [ 181.67857361]
 [ 194.68075562]
 [ 142.56730652]
 [  99.93167877]]
40 cost: 1.54791 
Prediction
 [[ 153.35549927]
 [ 183.80084229]
 [ 181.67712402]
 [ 194.6802063 ]
 [ 142.56915283]
 [  99.93531799]]
50 cost: 1.5442 
Prediction
 [[ 153.35202026]
 [ 183.80244446]
 [ 181.67562866]
 [ 194.67961121]
 [ 142.57096863]
 [  99.93890381]]
60 cost: 1.5

## Queue Runners 이용한 방법

In [3]:
import tensorflow as tf

filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'], shuffle=False, name='filename_queue')
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

X = tf.placeholder(tf.float32, [None, 3])
Y = tf.placeholder(tf.float32, [None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "cost:", cost_val, "\nPrediction\n", hy_val)
        
coord.request_stop()
coord.join(threads)

0 cost: 114317.0 
Prediction
 [[-150.74494934]
 [-183.24452209]
 [-179.31083679]
 [-196.98570251]
 [-138.95043945]
 [-105.48706818]
 [-150.74494934]
 [-183.24452209]
 [-179.31083679]
 [-196.98570251]]
10 cost: 7.22922 
Prediction
 [[ 138.66972351]
 [  99.1707077 ]
 [ 152.00012207]
 [ 180.71846008]
 [ 179.2624054 ]
 [ 193.50782776]
 [ 138.66972351]
 [  99.1707077 ]
 [ 152.00012207]
 [ 180.71846008]]
20 cost: 1.77133 
Prediction
 [[ 181.63912964]
 [ 196.09700012]
 [ 140.5160675 ]
 [ 100.53438568]
 [ 154.00267029]
 [ 183.13652039]
 [ 181.63912964]
 [ 196.09700012]
 [ 140.5160675 ]
 [ 100.53438568]]
30 cost: 2.26353 
Prediction
 [[ 153.98609924]
 [ 183.12657166]
 [ 181.62413025]
 [ 196.08146667]
 [ 140.51026917]
 [ 100.532547  ]
 [ 153.98609924]
 [ 183.12657166]
 [ 181.62413025]
 [ 196.08146667]]
40 cost: 2.25969 
Prediction
 [[ 140.45599365]
 [ 100.49503326]
 [ 153.91654968]
 [ 183.05303955]
 [ 181.54641724]
 [ 195.99769592]
 [ 140.45599365]
 [ 100.49503326]
 [ 153.91654968]
 [ 183.053039