# 2주차 실습 lab04 김성헌

## matrix 사용한 multi-variable linear regression

In [1]:
import tensorflow as tf

x_data = [[73., 80., 75.], 
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

X = tf.placeholder(tf.float32, [None, 3])
Y = tf.placeholder(tf.float32, [None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)

train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

0 Cost: 88394.9 
Prediction:
 [[-107.85084534]
 [-135.88343811]
 [-130.7428894 ]
 [-138.91812134]
 [-108.50853729]]
10 Cost: 27.8958 
Prediction:
 [[ 155.09907532]
 [ 180.19569397]
 [ 180.67826843]
 [ 200.2124176 ]
 [ 132.58784485]]
20 Cost: 26.9698 
Prediction:
 [[ 155.87736511]
 [ 181.16400146]
 [ 181.61535645]
 [ 201.23364258]
 [ 133.33398438]]
30 Cost: 26.8533 
Prediction:
 [[ 155.86247253]
 [ 181.1789093 ]
 [ 181.61305237]
 [ 201.23188782]
 [ 133.35289001]]
40 Cost: 26.7375 
Prediction:
 [[ 155.84521484]
 [ 181.19084167]
 [ 181.60791016]
 [ 201.22702026]
 [ 133.36953735]]
50 Cost: 26.6222 
Prediction:
 [[ 155.82800293]
 [ 181.20277405]
 [ 181.6027832 ]
 [ 201.22216797]
 [ 133.38613892]]
60 Cost: 26.5077 
Prediction:
 [[ 155.81085205]
 [ 181.21464539]
 [ 181.59767151]
 [ 201.21733093]
 [ 133.4026947 ]]
70 Cost: 26.3937 
Prediction:
 [[ 155.79371643]
 [ 181.22648621]
 [ 181.59257507]
 [ 201.21250916]
 [ 133.41920471]]
80 Cost: 26.2803 
Prediction:
 [[ 155.7766571 ]
 [ 181.23831177]


## 학습데이터 파일을 읽어와서 학습하기. numpy 사용

In [2]:
import tensorflow as tf
import numpy as np

tf.set_random_seed(777) # for reproducibility

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)

x_data = xy[:, :-1]
y_data = xy[:, [-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

X = tf.placeholder(tf.float32, [None, 3])
Y = tf.placeholder(tf.float32, [None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "cost:", cost_val, "\nPrediction\n", hy_val)
        
print("Your score will be " , sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis, feed_dict={X:[[60, 70, 110], [90, 100, 80]]}))

(6, 3) [[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]] 6
(6, 1) [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]]
0 cost: 7912.23 
Prediction
 [[ 74.1805954 ]
 [ 80.63321686]
 [ 83.98022461]
 [ 91.3227005 ]
 [ 59.21071243]
 [ 41.89090729]]
10 cost: 18.7817 
Prediction
 [[ 156.99079895]
 [ 180.22625732]
 [ 182.07872009]
 [ 198.1566925 ]
 [ 135.18450928]
 [  97.90641022]]
20 cost: 18.3149 
Prediction
 [[ 157.53268433]
 [ 180.91026306]
 [ 182.73564148]
 [ 198.87434387]
 [ 135.71247864]
 [  98.30292511]]
30 cost: 18.2107 
Prediction
 [[ 157.51747131]
 [ 180.92437744]
 [ 182.73266602]
 [ 198.87332153]
 [ 135.72944641]
 [  98.32271576]]
40 cost: 18.1073 
Prediction
 [[ 157.49855042]
 [ 180.93391418]
 [ 182.72523499]
 [ 198.86747742]
 [ 135.74293518]
 [  98.3398819 ]]
50 cost: 18.0045 
Prediction
 [[ 157.47967529]
 [ 180.94340515]
 [ 182.71781921]
 [ 198.86160278]
 [ 135.75634766]
 [  98.35697174]]
60 cost: 17

## Queue Runners 이용한 방법

In [3]:
import tensorflow as tf

filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'], shuffle=False, name='filename_queue')
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

X = tf.placeholder(tf.float32, [None, 3])
Y = tf.placeholder(tf.float32, [None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "cost:", cost_val, "\nPrediction\n", hy_val)
        
coord.request_stop()
coord.join(threads)

0 cost: 30286.3 
Prediction
 [[-7.88492298]
 [-2.53489661]
 [-6.15324497]
 [-6.32126904]
 [-0.41728717]
 [ 1.2950747 ]
 [-7.88492298]
 [-2.53489661]
 [-6.15324497]
 [-6.32126904]]
10 cost: 10.4431 
Prediction
 [[ 142.15322876]
 [ 106.38816833]
 [ 147.61442566]
 [ 184.38169861]
 [ 178.00917053]
 [ 194.23219299]
 [ 142.15322876]
 [ 106.38816833]
 [ 147.61442566]
 [ 184.38169861]]
20 cost: 8.80474 
Prediction
 [[ 179.05213928]
 [ 195.36520386]
 [ 142.94897461]
 [ 106.96794128]
 [ 148.50331116]
 [ 185.4289093 ]
 [ 179.05213928]
 [ 195.36520386]
 [ 142.94897461]
 [ 106.96794128]]
30 cost: 6.46461 
Prediction
 [[ 148.41827393]
 [ 185.30557251]
 [ 178.94171143]
 [ 195.24221802]
 [ 142.85189819]
 [ 106.88962555]
 [ 148.41827393]
 [ 185.30557251]
 [ 178.94171143]
 [ 195.24221802]]
40 cost: 9.86939 
Prediction
 [[ 143.03878784]
 [ 107.02082825]
 [ 148.64256287]
 [ 185.55447388]
 [ 179.19784546]
 [ 195.51846313]
 [ 143.03878784]
 [ 107.02082825]
 [ 148.64256287]
 [ 185.55447388]]
50 cost: 8.67708