# Normalization 테스트
내용 : Normalization 데이터로 학습 -> 원본 데이터로 테스트 

In [1]:
import tensorflow as tf
import numpy as np

def MinMaxScaler(data):
    numerator = data - np.min(data, 0) 
    denominator = np.max(data, 0) - np.min(data, 0) 
    # noise term prevents the zero division 
    return numerator / (denominator + 1e-7)

def Standardization(data):
    numerator = data - np.mean(data)
    denominator = np.std(data)
    return numerator / (denominator + 1e-7)
    
xy = np.loadtxt("random_sample_c_2_distortion.csv", delimiter=',', dtype=np.float32)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data[:5,:])

[[  9.36439941e+03   1.60173345e+00]
 [ -3.63125928e+03  -1.25541794e+00]
 [  1.35767031e+04  -1.39482510e+00]
 [ -1.81524160e+04   1.28897762e+00]
 [  2.21592012e+04   7.31841981e-01]]


In [2]:
x_data_Standardization = Standardization(x_data)
print(x_data_Standardization[:5,:])

[[ 0.7292881  -0.25044376]
 [-0.63058972 -0.25074273]
 [ 1.17006743 -0.25075731]
 [-2.15009689 -0.25047648]
 [ 2.06814814 -0.25053477]]


In [3]:
x_data_Normalize = MinMaxScaler(x_data)
print(x_data_Normalize[:5,:])

[[ 0.63212776  0.59649551]
 [ 0.43135348  0.25489101]
 [ 0.69720507  0.23822328]
 [ 0.20701128  0.55910206]
 [ 0.82979894  0.49249026]]


In [4]:
X = tf.placeholder(tf.float32, shape=(None,2))
Y = tf.placeholder(tf.float32, shape=(None,1))

W = tf.Variable(tf.random_normal([2,1]))
b = tf.Variable(tf.random_normal([1]))

hypothesis = tf.sigmoid(tf.matmul(X, W) + b)
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, _ = sess.run([cost, train], feed_dict={X: x_data_Standardization, Y: y_data})
    if step % 100 == 0:
        print(step, cost_val)
        

0 1.20825
100 0.916935
200 0.76152
300 0.695372
400 0.668744
500 0.657431
600 0.65222
700 0.649629
800 0.648253
900 0.647483
1000 0.647034
1100 0.646764
1200 0.646598
1300 0.646495
1400 0.646429
1500 0.646388
1600 0.646361
1700 0.646344
1800 0.646333
1900 0.646326
2000 0.646321


In [5]:
h, c, a = sess.run([hypothesis, cost, accuracy], feed_dict={X: x_data, Y: y_data})
print("\nHypothesis: ", h, "\nCost = ", c, "\nAccuracy = ", a)


Hypothesis:  [[ 1.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]

In [6]:
h2, c2, a2 = sess.run([hypothesis, cost, accuracy], feed_dict={X: x_data_Standardization, Y: y_data})
print("\nHypothesis: ", h2, "\nCost = ", c2, "\nAccuracy = ", a2)


Hypothesis:  [[ 0.55706716]
 [ 0.39794075]
 [ 0.60778278]
 [ 0.2435707 ]
 [ 0.70325482]
 [ 0.6673277 ]
 [ 0.2292027 ]
 [ 0.45466572]
 [ 0.16699579]
 [ 0.14227451]
 [ 0.49681643]
 [ 0.68453187]
 [ 0.5918377 ]
 [ 0.62616879]
 [ 0.73735619]
 [ 0.24800563]
 [ 0.37034738]
 [ 0.48992559]
 [ 0.5769763 ]
 [ 0.37685648]
 [ 0.51519233]
 [ 0.50477403]
 [ 0.50896561]
 [ 0.60544437]
 [ 0.54825521]
 [ 0.38949054]
 [ 0.34668347]
 [ 0.37004822]
 [ 0.76279241]
 [ 0.235819  ]
 [ 0.31253532]
 [ 0.23425969]
 [ 0.45163253]
 [ 0.31496945]
 [ 0.60606909]
 [ 0.54816502]
 [ 0.40631133]
 [ 0.2202746 ]
 [ 0.26247343]
 [ 0.61462134]
 [ 0.37698302]
 [ 0.53758168]
 [ 0.26728228]
 [ 0.29331237]
 [ 0.49792185]
 [ 0.37767863]
 [ 0.33798832]
 [ 0.26138875]
 [ 0.79311788]
 [ 0.60131621]
 [ 0.4371075 ]
 [ 0.49707004]
 [ 0.67643452]
 [ 0.33510077]
 [ 0.68845344]
 [ 0.34819472]
 [ 0.5872708 ]
 [ 0.67858297]
 [ 0.38877892]
 [ 0.8035177 ]
 [ 0.69046056]
 [ 0.37733024]
 [ 0.38457805]
 [ 0.21666341]
 [ 0.38379934]
 [ 0.322342