# Lab12-1

## Source - Hidden Size

In [1]:
import tensorflow as tf
import numpy as np
import pprint as pp

hidden_size = 2
cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size)

x_data = np.array([[[1, 0, 0, 0]]], dtype=np.float32)
outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
pp.pprint(outputs.eval(session=sess))
sess.close()



array([[[-0.12126965,  0.04771284]]], dtype=float32)


## Source - Sequence Length

In [1]:
import tensorflow as tf
import numpy as np
import pprint as pp

# One hot encoding
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

hidden_size = 2
cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size)

x_data = np.array([[h, e, l, l, o]], dtype=np.float32)
print(x_data.shape)
pp.pprint(x_data)

outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(outputs.shape)
pp.pprint(outputs.eval(session=sess))
sess.close()


(1, 5, 4)
array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]]], dtype=float32)
(1, 5, 2)
array([[[-0.11433306, -0.07929884],
        [-0.12271085, -0.23361538],
        [-0.22044176, -0.27179521],
        [-0.26037031, -0.34009811],
        [-0.23606877, -0.30080271]]], dtype=float32)


## Source - Batch Size

In [1]:
import tensorflow as tf
import numpy as np
import pprint as pp

# One hot encoding
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

hidden_size = 2
cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size)

x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)
print(x_data.shape)
pp.pprint(x_data)

outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(outputs.shape)
pp.pprint(outputs.eval(session=sess))
sess.close()


(3, 5, 4)
array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]],

       [[ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.]],

       [[ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]]], dtype=float32)
(3, 5, 2)
array([[[-0.03938178,  0.07989971],
        [-0.02605996, -0.05020123],
        [ 0.12074436, -0.12530623],
        [ 0.22557436, -0.17859218],
        [ 0.37780902, -0.08598676]],

       [[ 0.00755254, -0.09768543],
        [ 0.16275442, -0.02609918],
        [ 0.20845436, -0.11984451],
        [ 0.27806771, -0.17677672],
        [ 0.31966785, -0.21409507]],

       [[ 0.1384615 , -0.09079235],
        [ 0.23385607, -0.15665132],
        [ 0.18139948, -0.19575185],
        [ 0.16787945, -0.2219567 ],
 